name: Todd DeLuca's Blog
markdown: redcarpet
pygments: true
permalink: /post/:year/:month/:day/:title

authors:
  todd:
    name: Todd DeLuca
    display_name: Todd DeLuca
    gravatar: df681c7c4aba995332e6711f186e350f
    email: todddeluca@yahoo.com
    web: http://www.todddeluca.com
    twitter: todddeluca
    github: todddeluca
    linkedin: todddeluca